const wordsData = [
    "Abandonner",
    "Épis",
    "Lénine ",
    "Ride ",
    "Trousse ",
    "Lemercier",
    "Cinquantième ",
    "Lune ",
    "Recul ",
    "Etonné ",
    "Farcir ",
    "Foncé",
    "Concours",
    "Rousseau",
    "Vague ",
    "Bleuâtre ",
    "Moins ",
    "Flash",
    "Scooter",
    "Attacher",
    "Descendre",
    "Philathéiste",
    "salive",
    "Signer",
    "Tisane ",
    "Tulipe",
    "Surveillant",
    "Luge",
    "Blé",
    "Ciel",
    "Insicive",
    "Habillr",
    "Némo",
    "Oreiller",
    "Annulaire",
    "Cambrioleur",
    "Marseille",
    "Barbe",
    "Serveur ",
    "Baccalauréat",
    "Discothèque ",
    "Parquet",
    "Ouvert",
    "Steven",
    "Claque",
    "Blanchir",
    "Malentendant ",
    "Potiron ",
    "Chameau",
    "Francis ",
    "Solution ",
    "Scanner",
    "Enseignant ",
    "Ananas",
    "Grippe",
    "Goutter",
    "Son ",
    "Boulimique",
    "Chauve",
    "Réparer",
    "Cahier",
    "Capitale",
    "Algue",
    "Cactus",
    "Ambulance",
    "Grillade",
    "Léopard",
    "Accuser",
    "Pantalon",
    "Savon ",
    "Noircir",
    "Garer",
    "Ourson",
    "Gazelle",
    "Athènes",
    "Gauchiste",
    "Expirer",
    "Potage",
    "Odeur",
    "Ralentissement",
    "Changement ",
    "Ronflement ",
    "Omelette",
    "Trotinette",
    "Maternité",
    "Lendemain",
    "Guitare",
    "Japonais",
    "Embrasser",
    "Cocinelle",
    "Jamais ",
    "César",
    "Vertige",
    "Parapluie",
    "Cuire",
    "Succès",
    "François",
    "Théière",
    "Espelette",
    "Epouser",
    "Meurtrier",
    "Bergerie",
    "Gousse",
    "Couvert",
    "Moutarde",
    "Inférieur",
    "Tonne",
    "Amoureux",
    "Evier",
    "Selfie",
    "Parking",
    "Confiture",
    "Accent",
    "Garros",
    "Guidon",
    "Valise",
    "Dynamite",
    "Nu",
    "Maroc",
    "Empereur",
    "Tutoiement",
    "Hichcock",
    "Lycée",
    "Idem",
    "Froid",
    "Monnaie",
    "Changement ",
    "Blinis",
    "Marion",
    "Cinquième",
    "Freinage ",
    "Acier ",
    "Joggeur",
    "Portugal",
    "Droguerie",
    "Gruyère",
    "Bête",
    "Limace",
    "Accoudoir",
    "Balavoine",
    "Liquide",
    "Flaubert",
    "Tissu",
    "Enfance",
    "Atchoum",
    "Batterie",
    "Dent ",
    "Américain ",
    "Comédien ",
    "Robin",
    "Nathalie ",
    "Satan",
    "Zèbre ",
    "Lionceau",
    "Montréal",
    "Extériorité",
    "Octobre",
    "Texas ",
    "Tirer",
    "Scénario",
    "Sieste",
    "Velu",
    "Acrobate",
    "Éolienne",
    "Polluer",
    "Porc",
    "Goutte",
    "Gendarme",
    "Miroir",
    "Guitare",
    "Biscotte",
    "Rôtir",
    "Boomerang",
    "Patiner",
    "Bronche",
    "Bleuâtre ",
    "Pièce ",
    "Changement ",
    "Marchand ",
    "Bave ",
    "Volley",
    "Poppins",
    "Baby-sitter ",
    "Rennes",
    "Routier",
    "Juger",
    "Poil",
    "Ordinateur",
    "Cerveau",
    "Pépin ",
    "Mariage ",
    "Charles",
    "Tente",
    "Vernissage",
    "Tamise",
    "Bégayer",
    "Vœu",
    "Magie",
    "Franklin",
    "Franchir",
    "Sucre",
    "Jugnot",
    "Evier",
    "Globule",
    "Payer",
    "Pause",
    "Tartine ",
    "Pouce",
    "Nantes",
    "Emménager",
    "Ainsi",
    "Os",
    "Spaghetti",
    "Sissi",
    "Dossard",
    "Tiroir",
    "Examen ",
    "Clarté",
    "Voyager",
    "Foie-gras",
    "Mickey",
    "Pièce ",
    "Mouiller",
    "Salir",
    "Amazonie",
    "Emmanuel",
    "Série",
    "Boussole",
    "Lier",
    "Pommeau",
    "Election",
    "Reine",
    "Chaleur",
    "Bonus",
    "Balai",
    "Soustraction",
    "Bouteille",
    "Vacances",
    "Urgences",
    "Bruel",
    "Laid",
    "Argent",
    "Grenouille",
    "Porter",
    "Primaire",
    "Haricot",
    "Allemand",
    "Dinosaur",
    "Antille",
    "Echalote",
    "Mourir",
    "Normand",
    "Mourir",
    "Crevette",
    "Ratatouille",
    "Haine",
    "Entendre",
    "Augmentation",
    "Hirondelle",
    "Solaire",
    "Aluminium",
    "Bernadette",
    "Sureur",
    "Classer",
    "Mari",
    "Buvard",
    "Courageux",
    "Edouard",
    "Notre",
    "Trompe",
    "Transport",
    "Faim",
    "Pouce",
    "Zidane ",
    "Transat",
    "Parapluie",
    "Jardinier",
    "Cristal",
    "Gastronomie",
    "Babouche",
    "Calamar",
    "Vert",
    "Luc",
    "Dentelle",
    "Emission",
    "Lavande ",
    "Ordre",
    "Calisson",
    "Jeter",
    "Poison",
    "Maximal",
    "Gagnant",
    "Profession",
    "Escrime",
    "Direction",
    "Montagne",
    "Sauna",
    "Poirot",
    "Pantoufle",
    "Boxer",
    "Boucle",
    "Cupidon",
    "Loup",
    "Maman",
    "Ralentir",
    "Mammouth",
    "Lenteur",
    "Offrir",
    "Vanille",
    "Ambassadeur",
    "Rose",
    "Quasimodo",
    "Nombril" 
]

export default wordsData;